import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const _localizedStrings = {
    'en': {
      'app_name': 'Skin Glow',
      'skip': 'Skip',
      'next': 'Next',
      'login': 'Login',
      'register': 'Register',
      'continue_guest': 'Continue as guest',
      'forgot_password': 'Forgot password',
      'home': 'Home',
      'catalog': 'Catalog',
      'favorites': 'Favorites',
      'cart': 'Cart',
      'profile': 'Profile',
      'best_products': 'Our Best Product',
      'recommended': 'Recommended for you',
      'compare': 'Compare',
      'add_to_cart': 'Add to cart',
      'ai_info': 'AI info',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'primary_color': 'Primary color',
      'dark_mode': 'Dark Mode',
      'pull_refresh': 'Pull to refresh',
      'empty_favorites': 'No favorites yet',
      'search': 'Search',
      'search_products': 'Search products',
      'checkout': 'Checkout',
      'checkout_title': 'Checkout',
      'pay_now': 'Pay now',
      'select_address': 'Select an address',
      'add_new_address': 'Add new address',
      'choose_payment': 'Choose payment method',
      'payment_visa': 'Visa',
      'payment_mastercard': 'Mastercard',
      'payment_apple_pay': 'Apple Pay',
      'payment_cash': 'Cash on delivery',
      'order_summary': 'Order summary',
      'delivery_fee': 'Delivery fee',
      'order_success_title': 'Order placed',
      'order_success_body': 'Your self-care box is on the way.',
      'continue_shopping': 'Continue shopping',
      'empty_cart': 'Your cart is empty',
      'orders': 'My Orders',
      'help': 'Help Center',
      'faq': 'Frequently asked questions',
      'faq_shipping_q': 'How long does delivery take?',
      'faq_shipping_a': 'Orders ship within 1-2 days and arrive in 2-4 business days.',
      'faq_returns_q': 'Can I return an opened product?',
      'faq_returns_a': 'We accept returns on gently used items within 14 days.',
      'faq_routine_q': 'How do I build my routine?',
      'faq_routine_a': 'Start with cleanser and moisturizer, then layer serums slowly.',
      'contact_us': 'Contact us',
      'email_support': 'Email support',
      'about': 'About app',
      'about_description':
          'A mock skin-care boutique to explore routines, compare products, and check out in style.',
      'app_version': 'Version',
      'app_story': 'Why you will love Glow',
      'mission': 'Personalized care with zero pressure—everything happens locally on your device.',
      'highlights': 'Highlights',
      'privacy': 'Privacy',
      'terms': 'Terms',
      'ai_dialog': 'AI explanation coming soon',
      'no_items_compare': 'Add at least two products to compare.',
      'notifications': 'Notifications',
      'mark_all': 'Mark all',
      'no_notifications': 'Nothing new yet',
      'rewards': 'Rewards',
      'current_points': 'Current points',
      'next_tier_hint': 'Collect 360 more points to reach Rose Gold tier.',
      'perks': 'Perks you unlock',
      'perk_fast_shipping': 'Priority shipping on every order',
      'perk_skin_coach': '1:1 skin coach mini sessions',
      'perk_gifts': 'Surprise deluxe mini in monthly orders',
      'addresses': 'Addresses',
      'add_address': 'Add address',
      'no_addresses': 'No saved addresses yet',
      'label': 'Label',
      'details': 'Details',
      'cancel': 'Cancel',
      'save': 'Save',
      'new_address': 'New address',
      'skin_quiz': 'Skin quiz',
      'routine_planner': 'Routine planner',
      'morning': 'Morning',
      'evening': 'Evening',
      'see_recommendations': 'See recommendations',
      'quiz_result_title': 'Routine focus',
      'quiz_result_body': 'We recommend starting with',
      'close': 'Close',
      'order': 'Order',
      'status': 'Status',
      'delivery': 'Delivery',
      'payment_method': 'Payment method',
      'items': 'Items',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'currency': 'USD',
      'guest': 'Guest',
      'logout': 'Logout',
      'address': 'Address',
      'wellness_hub': 'Glow Studio',
      'take_quiz': 'Take skin quiz',
      'plan_routine': 'Plan routine',
      'care_plan': 'Care plan',
      'track_rewards': 'Track rewards',
      'ingredient_library': 'Ingredient library',
      'search_ingredients': 'Search ingredients',
      'no_ingredients': 'No ingredients match your filters yet',
      'benefits': 'Benefits',
      'caution': 'Caution',
      'skin_health': 'Skin health',
      'skin_insights': 'Skin insights',
      'wellness_timeline': 'Wellness timeline',
      'routine_calendar': 'Routine calendar',
      'hydration': 'Hydration',
      'radiance': 'Radiance',
      'breakouts': 'Breakouts',
      'trend_week': 'This week\'s trends',
      'hydration_avg': 'Hydration average',
      'radiance_avg': 'Radiance average',
      'breakouts_avg': 'Fewer breakouts',
      'trend_hint': 'Track hydration, glow, and flare-ups to spot trends.',
      'recent_notes': 'Recent notes',
      'log_today': 'Log today',
      'log_entry': 'Logged hydration boost with calming mask.',
      'no_metrics': 'No skin check-ins yet',
      'latest_checkins': 'Latest check-ins',
      'insight_tips': 'Insight tips',
      'no_insights_yet': 'Insights will appear after a few logs.',
      'mark_day_done': 'Mark day done',
      'day_done': 'Done',
      'no_timeline': 'No milestones yet—log a check-in to start.',
      'reminders': 'Reminders',
      'morning_reminder': 'Morning reminder',
      'evening_reminder': 'Evening reminder',
      'reminder_time': 'Reminder time',
      'update_time': 'Update time',
      'reminder_note': 'Keep gentle nudges for sunscreen, hydration, and bedtime routines.',
      'all': 'All',
      'concern_brightening': 'Brightening',
      'concern_soothing': 'Soothing',
      'concern_hydration': 'Hydration',
      'concern_acne': 'Blemish care',
      'concern_texture': 'Texture',
      'concern_oil': 'Oil control',
      'filters': 'Filters',
      'price_range': 'Price range',
      'categories': 'Categories',
      'apply': 'Apply',
      'clear': 'Clear',
      'empty_catalog': 'No products match your filters yet',
      'glow_journal': 'Glow Journal',
      'journal_intro': 'Short reads from our skin coaches.',
      'read_now': 'Read now',
      'minutes_read': 'min read',
      'skin_diary': 'Skin diary',
      'diary_intro': 'Log how your skin feels each day.',
      'add_entry': 'Add entry',
      'mood': 'Mood',
      'note': 'Note',
      'entry_hint': 'Today my skin feels...',
      'no_entries': 'No diary entries yet',
      'book_consultation': 'Book consultation',
      'consultation_intro': 'Chat with a specialist to refine your routine.',
      'next_session': 'Next session',
      'pick_slot': 'Pick a slot',
      'slot_booked': 'Session booked',
      'minutes': 'minutes',
      'bundles': 'Gift sets',
      'curated_sets': 'Curated sets',
      'bundle_includes': 'What is inside',
      'add_bundle': 'Add bundle to cart',
      'bundle_added': 'Bundle items added to cart',
      'track_order': 'Track order',
      'carrier': 'Carrier',
      'tracking_code': 'Tracking code',
      'order_timeline': 'Delivery timeline',
      'no_tracking': 'Tracking will appear once the courier scans your package.',
      'reorder': 'Reorder items',
      'reorder_added': 'Items added back to your cart',
      'skin_goals': 'Skin goals',
      'goal_actions': 'Steps to complete',
      'no_goals': 'No goals yet — set one from the wellness hub.',
      'focus': 'Focus',
      'weekly_plan_hint': 'Follow this lightweight weekly plan to balance your skin and track wins.',
      'coach_tip': 'Coach tip',
      'reset_progress': 'Reset progress',
      'referrals': 'Referrals',
      'invite_friends': 'Invite friends',
      'share_code': 'Share this code for rewards',
      'copy_code': 'Copy code',
      'active_coupons': 'Active coupons',
      'coupon_applied': 'Coupon applied',
      'applied': 'Applied',
      'remove': 'Remove',
      'apply_coupon': 'Apply coupon',
      'coupon_center': 'Coupon center',
      'no_coupons': 'No coupons available yet',
      'tap_apply': 'Tap apply to activate',
      'expires_on': 'Expires on',
      'expires': 'Expires',
      'subscriptions': 'Subscriptions',
      'empty_subscriptions': 'No subscriptions yet',
      'frequency': 'Frequency',
      'next_delivery': 'Next delivery',
      'adjust_frequency': 'Adjust cadence',
      'skip_next': 'Skip next',
      'pause': 'Pause',
      'resume': 'Resume',
      'challenges': 'Challenges',
      'empty_challenges': 'No challenges yet — pick one from Glow Studio.',
      'challenge_summary': 'Challenge progress',
      'challenge_detail': 'Stay hydrated and consistent to unlock perks.',
      'no_challenges': 'No challenges yet',
      'complete': 'complete',
      'skin_report': 'Skin report',
      'diary_entries': 'Diary entries',
      'entries_logged': 'entries logged',
      'goal_progress': 'Goal progress',
      'goal_progress_detail': '{p}% of your steps completed',
      'points_balance': '{p} points saved',
      'wellness_dashboard': 'Wellness dashboard',
      'daily_overview': 'Daily overview',
      'routine_streak': 'Routine streak',
      'completed_routines': 'Completed routines',
      'referrals_shared': 'Referrals shared',
      'actions': 'Actions',
      'complete_routine': 'Complete routine',
      'reset_streak': 'Reset streak',
      'steps_done': 'steps done',
      'days': 'days',
      'copied': 'Copied to clipboard',
    },
    'ar': {
      'app_name': 'توهج البشرة',
      'skip': 'تخطي',
      'next': 'التالي',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'continue_guest': 'المتابعة كضيف',
      'forgot_password': 'نسيت كلمة المرور',
      'home': 'الرئيسية',
      'catalog': 'الكتالوج',
      'favorites': 'المفضلة',
      'cart': 'السلة',
      'profile': 'الحساب',
      'best_products': 'أفضل منتجاتنا',
      'recommended': 'مقترحة لك',
      'compare': 'مقارنة',
      'add_to_cart': 'أضف للسلة',
      'ai_info': 'معلومة بالذكاء الاصطناعي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'السمة',
      'primary_color': 'اللون الرئيسي',
      'dark_mode': 'الوضع الداكن',
      'pull_refresh': 'اسحب للتحديث',
      'empty_favorites': 'لا توجد مفضلة بعد',
      'search': 'بحث',
      'search_products': 'ابحث عن المنتجات',
      'checkout': 'الدفع',
      'checkout_title': 'الدفع',
      'pay_now': 'ادفع الآن',
      'select_address': 'اختر عنواناً',
      'add_new_address': 'أضف عنواناً جديداً',
      'choose_payment': 'اختر طريقة الدفع',
      'payment_visa': 'فيزا',
      'payment_mastercard': 'ماستركارد',
      'payment_apple_pay': 'أبل باي',
      'payment_cash': 'الدفع عند الاستلام',
      'order_summary': 'ملخص الطلب',
      'delivery_fee': 'رسوم التوصيل',
      'order_success_title': 'تم تأكيد الطلب',
      'order_success_body': 'صندوق العناية في الطريق إليك.',
      'continue_shopping': 'متابعة التسوق',
      'empty_cart': 'سلتك فارغة',
      'orders': 'طلباتي',
      'help': 'مركز المساعدة',
      'faq': 'الأسئلة الشائعة',
      'faq_shipping_q': 'كم يستغرق التوصيل؟',
      'faq_shipping_a': 'نشحن خلال يومين ويصل الطلب خلال ٢-٤ أيام عمل.',
      'faq_returns_q': 'هل يمكن إرجاع منتج مفتوح؟',
      'faq_returns_a': 'نقبل الإرجاع للمنتجات المستخدمة بلطف خلال ١٤ يوماً.',
      'faq_routine_q': 'كيف أبني روتيني؟',
      'faq_routine_a': 'ابدأي بمنظف ومرطب ثم أضيفي السيرومات تدريجياً.',
      'contact_us': 'تواصل معنا',
      'email_support': 'الدعم عبر البريد',
      'about': 'حول التطبيق',
      'about_description':
          'متجر تجريبي للعناية بالبشرة لتجربة الروتينات ومقارنة المنتجات والدفع بتجربة أنيقة.',
      'app_version': 'الإصدار',
      'app_story': 'لماذا ستحب توهج',
      'mission': 'عناية شخصية بدون ضغط، كل شيء يحدث محلياً على جهازك.',
      'highlights': 'المميزات',
      'privacy': 'الخصوصية',
      'terms': 'الشروط',
      'ai_dialog': 'شرح الذكاء الاصطناعي قريباً',
      'no_items_compare': 'أضف منتجين على الأقل للمقارنة.',
      'notifications': 'الإشعارات',
      'mark_all': 'تحديد الكل كمقروء',
      'no_notifications': 'لا جديد بعد',
      'rewards': 'المكافآت',
      'current_points': 'النقاط الحالية',
      'next_tier_hint': 'اجمع ٣٦٠ نقطة إضافية للوصول لمرتبة الروز جولد.',
      'perks': 'المزايا التي تحصل عليها',
      'perk_fast_shipping': 'شحن أولوية لكل طلب',
      'perk_skin_coach': 'جلسات مصغرة مع مدرب بشرة',
      'perk_gifts': 'هدايا مصغرة شهرية',
      'addresses': 'العناوين',
      'add_address': 'أضف عنواناً',
      'no_addresses': 'لا توجد عناوين محفوظة',
      'label': 'اسم العنوان',
      'details': 'تفاصيل',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'new_address': 'عنوان جديد',
      'skin_quiz': 'اختبار البشرة',
      'routine_planner': 'مخطط الروتين',
      'morning': 'الصباح',
      'evening': 'المساء',
      'see_recommendations': 'عرض التوصيات',
      'quiz_result_title': 'تركيز الروتين',
      'quiz_result_body': 'ننصحك بالبدء مع',
      'close': 'إغلاق',
      'order': 'طلب',
      'status': 'الحالة',
      'delivery': 'التوصيل',
      'payment_method': 'طريقة الدفع',
      'items': 'العناصر',
      'subtotal': 'المجموع الفرعي',
      'total': 'الإجمالي',
      'currency': 'ريال',
      'guest': 'ضيف',
      'logout': 'تسجيل الخروج',
      'address': 'العنوان',
      'wellness_hub': 'استوديو العناية',
      'take_quiz': 'ابدأ اختبار البشرة',
      'plan_routine': 'خطط للروتين',
      'care_plan': 'خطة العناية',
      'track_rewards': 'تابع المكافآت',
      'ingredient_library': 'مكتبة المكونات',
      'search_ingredients': 'ابحث عن المكونات',
      'no_ingredients': 'لا توجد مكونات مطابقة حالياً',
      'benefits': 'الفوائد',
      'caution': 'تنبيه',
      'skin_health': 'صحة البشرة',
      'skin_insights': 'رؤى البشرة',
      'wellness_timeline': 'الخط الزمني للعافية',
      'routine_calendar': 'تقويم الروتين',
      'hydration': 'الترطيب',
      'radiance': 'الإشراقة',
      'breakouts': 'الالتهابات',
      'trend_hint': 'تتبع الترطيب والإشراقة والالتهابات لمعرفة الأنماط.',
      'trend_week': 'اتجاهات هذا الأسبوع',
      'hydration_avg': 'متوسط الترطيب',
      'radiance_avg': 'متوسط الإشراقة',
      'breakouts_avg': 'حبوب أقل',
      'recent_notes': 'ملاحظات حديثة',
      'log_today': 'سجل اليوم',
      'log_entry': 'تم تسجيل دفعة ترطيب مع قناع مهدئ.',
      'no_metrics': 'لا يوجد تسجيلات للبشرة بعد',
      'latest_checkins': 'أحدث القياسات',
      'insight_tips': 'نصائح مخصصة',
      'no_insights_yet': 'ستظهر الرؤى بعد بعض التسجيلات.',
      'mark_day_done': 'وضع علامة مكتمل',
      'day_done': 'مكتمل',
      'no_timeline': 'لا توجد إنجازات بعد—ابدأ بتسجيل قياس.',
      'reminders': 'تذكيرات',
      'morning_reminder': 'تذكير الصباح',
      'evening_reminder': 'تذكير المساء',
      'reminder_time': 'وقت التذكير',
      'update_time': 'تحديث الوقت',
      'reminder_note': 'حافظ على تنبيهات لطيفة للواقي والشرب وروتين النوم.',
      'all': 'الكل',
      'concern_brightening': 'تفتيح',
      'concern_soothing': 'تهدئة',
      'concern_hydration': 'ترطيب',
      'concern_acne': 'عناية بالبثور',
      'concern_texture': 'ملمس البشرة',
      'concern_oil': 'توازن الدهون',
      'filters': 'التصفية',
      'price_range': 'نطاق السعر',
      'categories': 'الفئات',
      'apply': 'تطبيق',
      'clear': 'مسح',
      'empty_catalog': 'لا توجد منتجات مطابقة للمعايير',
      'glow_journal': 'مجلة التوهج',
      'journal_intro': 'قراءات قصيرة من مدربي البشرة لدينا.',
      'read_now': 'اقرأ الآن',
      'minutes_read': 'دقيقة قراءة',
      'skin_diary': 'مذكرات البشرة',
      'diary_intro': 'دوّن شعور بشرتك يومياً.',
      'add_entry': 'إضافة تدوينة',
      'mood': 'الحالة',
      'note': 'ملاحظة',
      'entry_hint': 'اليوم بشرتي تشعر بـ...',
      'no_entries': 'لا توجد تدوينات بعد',
      'book_consultation': 'احجزي استشارة',
      'consultation_intro': 'تحدثي مع مختص لتحسين روتينك.',
      'next_session': 'الموعد القادم',
      'pick_slot': 'اختاري وقتاً',
      'slot_booked': 'تم حجز الجلسة',
      'minutes': 'دقائق',
      'bundles': 'مجموعات هدايا',
      'curated_sets': 'مجموعات مختارة',
      'bundle_includes': 'ما بداخل المجموعة',
      'add_bundle': 'أضف المجموعة للسلة',
      'bundle_added': 'تمت إضافة عناصر المجموعة للسلة',
      'track_order': 'تتبع الطلب',
      'carrier': 'شركة الشحن',
      'tracking_code': 'رقم التتبع',
      'order_timeline': 'خط سير التوصيل',
      'no_tracking': 'سيظهر التتبع بعد استلام شركة الشحن للطلب.',
      'reorder': 'إعادة الطلب',
      'reorder_added': 'تمت إضافة العناصر للسلة مجدداً',
      'skin_goals': 'أهداف البشرة',
      'goal_actions': 'خطوات التنفيذ',
      'no_goals': 'لا توجد أهداف بعد — حددي هدفاً من استوديو العناية.',
      'focus': 'التركيز',
      'weekly_plan_hint': 'اتبع خطة أسبوعية خفيفة لموازنة البشرة وتتبع إنجازاتك.',
      'coach_tip': 'نصيحة المدرب',
      'reset_progress': 'إعادة تعيين التقدم',
      'referrals': 'الإحالات',
      'invite_friends': 'ادعي صديقاتك',
      'share_code': 'شاركي هذا الكود لتحصلي على مكافآت',
      'copy_code': 'نسخ الكود',
      'active_coupons': 'القسائم المفعلة',
      'coupon_applied': 'تم تطبيق القسيمة',
      'applied': 'مُطبقة',
      'remove': 'إزالة',
      'apply_coupon': 'تفعيل القسيمة',
      'coupon_center': 'مركز الكوبونات',
      'no_coupons': 'لا توجد كوبونات حالياً',
      'tap_apply': 'اضغطي للتفعيل',
      'expires_on': 'ينتهي في',
      'expires': 'ينتهي في',
      'subscriptions': 'الاشتراكات',
      'empty_subscriptions': 'لا توجد اشتراكات بعد',
      'frequency': 'التكرار',
      'next_delivery': 'التوصيل القادم',
      'adjust_frequency': 'تغيير الجدولة',
      'skip_next': 'تخطي الشحنة القادمة',
      'pause': 'إيقاف مؤقت',
      'resume': 'استئناف',
      'challenges': 'التحديات',
      'empty_challenges': 'لا توجد تحديات بعد — اختاري واحداً من الاستوديو.',
      'challenge_summary': 'تقدم التحدي',
      'challenge_detail': 'استمري بالترطيب والالتزام لتحصلي على المكافآت.',
      'no_challenges': 'لا توجد تحديات بعد',
      'complete': 'مكتمل',
      'skin_report': 'تقرير البشرة',
      'diary_entries': 'تدوينات المذكرات',
      'entries_logged': 'تدوينات مسجلة',
      'goal_progress': 'تقدم الأهداف',
      'goal_progress_detail': 'اكتمل {p}% من الخطوات',
      'points_balance': '{p} نقطة محفوظة',
      'wellness_dashboard': 'لوحة العافية',
      'daily_overview': 'نظرة يومية',
      'routine_streak': 'سلسلة الروتين',
      'completed_routines': 'الروتينات المنجزة',
      'referrals_shared': 'الإحالات المرسلة',
      'actions': 'إجراءات',
      'complete_routine': 'إنهاء روتين',
      'reset_streak': 'إعادة السلسلة',
      'steps_done': 'خطوات مكتملة',
      'days': 'يوم',
      'copied': 'تم النسخ',
    },
  };

  static const localizationsDelegates = [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    _AppLocalizationsDelegate(),
  ];

  static const supportedLocales = [Locale('en'), Locale('ar')];

  String t(String key) => _localizedStrings[locale.languageCode]?[key] ?? key;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
