import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const _localizedStrings = {
    'en': {
      'app_name': 'Skin Glow',
      'skip': 'Skip',
      'next': 'Next',
      'login': 'Login',
      'register': 'Register',
      'continue_guest': 'Continue as guest',
      'forgot_password': 'Forgot password',
      'home': 'Home',
      'catalog': 'Catalog',
      'favorites': 'Favorites',
      'cart': 'Cart',
      'profile': 'Profile',
      'best_products': 'Our Best Product',
      'recommended': 'Recommended for you',
      'compare': 'Compare',
      'add_to_cart': 'Add to cart',
      'ai_info': 'AI info',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'primary_color': 'Primary color',
      'dark_mode': 'Dark Mode',
      'pull_refresh': 'Pull to refresh',
      'empty_favorites': 'No favorites yet',
      'search': 'Search',
      'search_products': 'Search products',
      'checkout': 'Checkout',
      'checkout_title': 'Checkout',
      'pay_now': 'Pay now',
      'select_address': 'Select an address',
      'add_new_address': 'Add new address',
      'choose_payment': 'Choose payment method',
      'payment_visa': 'Visa',
      'payment_mastercard': 'Mastercard',
      'payment_apple_pay': 'Apple Pay',
      'payment_cash': 'Cash on delivery',
      'order_summary': 'Order summary',
      'delivery_fee': 'Delivery fee',
      'order_success_title': 'Order placed',
      'order_success_body': 'Your self-care box is on the way.',
      'continue_shopping': 'Continue shopping',
      'empty_cart': 'Your cart is empty',
      'orders': 'My Orders',
      'help': 'Help Center',
      'faq': 'Frequently asked questions',
      'faq_shipping_q': 'How long does delivery take?',
      'faq_shipping_a': 'Orders ship within 1-2 days and arrive in 2-4 business days.',
      'faq_returns_q': 'Can I return an opened product?',
      'faq_returns_a': 'We accept returns on gently used items within 14 days.',
      'faq_routine_q': 'How do I build my routine?',
      'faq_routine_a': 'Start with cleanser and moisturizer, then layer serums slowly.',
      'contact_us': 'Contact us',
      'email_support': 'Email support',
      'about': 'About app',
      'about_description':
          'A mock skin-care boutique to explore routines, compare products, and check out in style.',
      'app_version': 'Version',
      'app_story': 'Why you will love Glow',
      'mission': 'Personalized care with zero pressure—everything happens locally on your device.',
      'highlights': 'Highlights',
      'privacy': 'Privacy',
      'terms': 'Terms',
      'ai_dialog': 'AI explanation coming soon',
      'no_items_compare': 'Add at least two products to compare.',
      'notifications': 'Notifications',
      'mark_all': 'Mark all',
      'no_notifications': 'Nothing new yet',
      'rewards': 'Rewards',
      'current_points': 'Current points',
      'next_tier_hint': 'Collect 360 more points to reach Rose Gold tier.',
      'perks': 'Perks you unlock',
      'perk_fast_shipping': 'Priority shipping on every order',
      'perk_skin_coach': '1:1 skin coach mini sessions',
      'perk_gifts': 'Surprise deluxe mini in monthly orders',
      'addresses': 'Addresses',
      'add_address': 'Add address',
      'no_addresses': 'No saved addresses yet',
      'label': 'Label',
      'details': 'Details',
      'cancel': 'Cancel',
      'save': 'Save',
      'new_address': 'New address',
      'skin_quiz': 'Skin quiz',
      'routine_planner': 'Routine planner',
      'morning': 'Morning',
      'evening': 'Evening',
      'see_recommendations': 'See recommendations',
      'quiz_result_title': 'Routine focus',
      'quiz_result_body': 'We recommend starting with',
      'close': 'Close',
      'order': 'Order',
      'status': 'Status',
      'delivery': 'Delivery',
      'payment_method': 'Payment method',
      'items': 'Items',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'currency': 'USD',
      'guest': 'Guest',
      'logout': 'Logout',
      'address': 'Address',
      'wellness_hub': 'Glow Studio',
      'take_quiz': 'Take skin quiz',
      'plan_routine': 'Plan routine',
      'track_rewards': 'Track rewards',
      'filters': 'Filters',
      'price_range': 'Price range',
      'categories': 'Categories',
      'apply': 'Apply',
      'clear': 'Clear',
      'empty_catalog': 'No products match your filters yet',
      'glow_journal': 'Glow Journal',
      'journal_intro': 'Short reads from our skin coaches.',
      'read_now': 'Read now',
      'minutes_read': 'min read',
      'skin_diary': 'Skin diary',
      'diary_intro': 'Log how your skin feels each day.',
      'add_entry': 'Add entry',
      'mood': 'Mood',
      'note': 'Note',
      'entry_hint': 'Today my skin feels...',
      'no_entries': 'No diary entries yet',
      'book_consultation': 'Book consultation',
      'consultation_intro': 'Chat with a specialist to refine your routine.',
      'next_session': 'Next session',
      'pick_slot': 'Pick a slot',
      'slot_booked': 'Session booked',
      'minutes': 'minutes',
    },
    'ar': {
      'app_name': 'توهج البشرة',
      'skip': 'تخطي',
      'next': 'التالي',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'continue_guest': 'المتابعة كضيف',
      'forgot_password': 'نسيت كلمة المرور',
      'home': 'الرئيسية',
      'catalog': 'الكتالوج',
      'favorites': 'المفضلة',
      'cart': 'السلة',
      'profile': 'الحساب',
      'best_products': 'أفضل منتجاتنا',
      'recommended': 'مقترحة لك',
      'compare': 'مقارنة',
      'add_to_cart': 'أضف للسلة',
      'ai_info': 'معلومة بالذكاء الاصطناعي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'السمة',
      'primary_color': 'اللون الرئيسي',
      'dark_mode': 'الوضع الداكن',
      'pull_refresh': 'اسحب للتحديث',
      'empty_favorites': 'لا توجد مفضلة بعد',
      'search': 'بحث',
      'search_products': 'ابحث عن المنتجات',
      'checkout': 'الدفع',
      'checkout_title': 'الدفع',
      'pay_now': 'ادفع الآن',
      'select_address': 'اختر عنواناً',
      'add_new_address': 'أضف عنواناً جديداً',
      'choose_payment': 'اختر طريقة الدفع',
      'payment_visa': 'فيزا',
      'payment_mastercard': 'ماستركارد',
      'payment_apple_pay': 'أبل باي',
      'payment_cash': 'الدفع عند الاستلام',
      'order_summary': 'ملخص الطلب',
      'delivery_fee': 'رسوم التوصيل',
      'order_success_title': 'تم تأكيد الطلب',
      'order_success_body': 'صندوق العناية في الطريق إليك.',
      'continue_shopping': 'متابعة التسوق',
      'empty_cart': 'سلتك فارغة',
      'orders': 'طلباتي',
      'help': 'مركز المساعدة',
      'faq': 'الأسئلة الشائعة',
      'faq_shipping_q': 'كم يستغرق التوصيل؟',
      'faq_shipping_a': 'نشحن خلال يومين ويصل الطلب خلال ٢-٤ أيام عمل.',
      'faq_returns_q': 'هل يمكن إرجاع منتج مفتوح؟',
      'faq_returns_a': 'نقبل الإرجاع للمنتجات المستخدمة بلطف خلال ١٤ يوماً.',
      'faq_routine_q': 'كيف أبني روتيني؟',
      'faq_routine_a': 'ابدأي بمنظف ومرطب ثم أضيفي السيرومات تدريجياً.',
      'contact_us': 'تواصل معنا',
      'email_support': 'الدعم عبر البريد',
      'about': 'حول التطبيق',
      'about_description':
          'متجر تجريبي للعناية بالبشرة لتجربة الروتينات ومقارنة المنتجات والدفع بتجربة أنيقة.',
      'app_version': 'الإصدار',
      'app_story': 'لماذا ستحب توهج',
      'mission': 'عناية شخصية بدون ضغط، كل شيء يحدث محلياً على جهازك.',
      'highlights': 'المميزات',
      'privacy': 'الخصوصية',
      'terms': 'الشروط',
      'ai_dialog': 'شرح الذكاء الاصطناعي قريباً',
      'no_items_compare': 'أضف منتجين على الأقل للمقارنة.',
      'notifications': 'الإشعارات',
      'mark_all': 'تحديد الكل كمقروء',
      'no_notifications': 'لا جديد بعد',
      'rewards': 'المكافآت',
      'current_points': 'النقاط الحالية',
      'next_tier_hint': 'اجمع ٣٦٠ نقطة إضافية للوصول لمرتبة الروز جولد.',
      'perks': 'المزايا التي تحصل عليها',
      'perk_fast_shipping': 'شحن أولوية لكل طلب',
      'perk_skin_coach': 'جلسات مصغرة مع مدرب بشرة',
      'perk_gifts': 'هدايا مصغرة شهرية',
      'addresses': 'العناوين',
      'add_address': 'أضف عنواناً',
      'no_addresses': 'لا توجد عناوين محفوظة',
      'label': 'اسم العنوان',
      'details': 'تفاصيل',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'new_address': 'عنوان جديد',
      'skin_quiz': 'اختبار البشرة',
      'routine_planner': 'مخطط الروتين',
      'morning': 'الصباح',
      'evening': 'المساء',
      'see_recommendations': 'عرض التوصيات',
      'quiz_result_title': 'تركيز الروتين',
      'quiz_result_body': 'ننصحك بالبدء مع',
      'close': 'إغلاق',
      'order': 'طلب',
      'status': 'الحالة',
      'delivery': 'التوصيل',
      'payment_method': 'طريقة الدفع',
      'items': 'العناصر',
      'subtotal': 'المجموع الفرعي',
      'total': 'الإجمالي',
      'currency': 'ريال',
      'guest': 'ضيف',
      'logout': 'تسجيل الخروج',
      'address': 'العنوان',
      'wellness_hub': 'استوديو العناية',
      'take_quiz': 'ابدأ اختبار البشرة',
      'plan_routine': 'خطط للروتين',
      'track_rewards': 'تابع المكافآت',
      'filters': 'التصفية',
      'price_range': 'نطاق السعر',
      'categories': 'الفئات',
      'apply': 'تطبيق',
      'clear': 'مسح',
      'empty_catalog': 'لا توجد منتجات مطابقة للمعايير',
      'glow_journal': 'مجلة التوهج',
      'journal_intro': 'قراءات قصيرة من مدربي البشرة لدينا.',
      'read_now': 'اقرأ الآن',
      'minutes_read': 'دقيقة قراءة',
      'skin_diary': 'مذكرات البشرة',
      'diary_intro': 'دوّن شعور بشرتك يومياً.',
      'add_entry': 'إضافة تدوينة',
      'mood': 'الحالة',
      'note': 'ملاحظة',
      'entry_hint': 'اليوم بشرتي تشعر بـ...',
      'no_entries': 'لا توجد تدوينات بعد',
      'book_consultation': 'احجزي استشارة',
      'consultation_intro': 'تحدثي مع مختص لتحسين روتينك.',
      'next_session': 'الموعد القادم',
      'pick_slot': 'اختاري وقتاً',
      'slot_booked': 'تم حجز الجلسة',
      'minutes': 'دقائق',
    },
  };

  static const localizationsDelegates = [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    _AppLocalizationsDelegate(),
  ];

  static const supportedLocales = [Locale('en'), Locale('ar')];

  String t(String key) => _localizedStrings[locale.languageCode]?[key] ?? key;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
